//------------------------------------------------------------------------
// Copyright(c) 2026 GullDSP.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Phathom.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Phathom VST3 (64Bit)"
#else
#define stringFileDescription	"Phathom VST3"
#endif
#define stringCompanyName		"GullDSP\0"
#define stringLegalCopyright	"Copyright(c) 2026 GullDSP."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
